//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxarifadoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDAlmoxarifado : DbContext
    {
        public BDAlmoxarifado()
            : base("name=BDAlmoxarifado")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<ENTRADA> ENTRADA { get; set; }
        public virtual DbSet<ItemsEntrada> ItemsEntrada { get; set; }
        public virtual DbSet<ItemsSaida> ItemsSaida { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Saida> Saida { get; set; }
        public virtual DbSet<ProdutoSaida> ProdutoSaida { get; set; }
    }
}
