//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxarifadoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsEntrada
    {
        public int ItemID { get; set; }
        public int ItemQuantidade { get; set; }
        public decimal ItemPreco { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public int ENTID { get; set; }
        public int ProID { get; set; }
    
        public virtual ENTRADA ENTRADA { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
