//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxarifadoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoSaida
    {
        public int ID { get; set; }
        public int Quantidade { get; set; }
        public int ID_da_saida { get; set; }
        public string Nome_do_produto { get; set; }
        public System.DateTime Data { get; set; }
    }
}
