//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxarifadoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saida()
        {
            this.ItemsSaida = new HashSet<ItemsSaida>();
        }
    
        public int SaidaID { get; set; }
        public System.DateTime SaidaData { get; set; }
        public string SaidaObeservacao { get; set; }
        public int ColID { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsSaida> ItemsSaida { get; set; }
    }
}
